### PR TITLE
Merge scm-lin to master - Added new repos 

### PR DESCRIPTION
**Pull request by fogarl1**
- [ ] I have read the [CONTRIBUTION GUIDE][contributing]
- [ ] This is a bug
- [ ] This is a feature request
- [ ] This is a syntax/style fix
- [ ] This is an improvement to code quality

---
**Please describe your changes below:** 

(Note: A clear description of changes is required to approve any pull requests)
 
_"Changed the implementation for verification because..."_

[contributing]: http://dellemc-symphony.readthedocs.io/en/latest/contributingtosymphony.html

### CODE REVIEW

**Comment by fogarl1** [comment]
I didn't add component-rackhd in the documentation repo as it is not ready for opensource

**Comment by giddyelysium** [comment]
PR will wait until the middle of next week due to all re-version stories, once that 4 re-version of the group's are completed we will merge this. @heypaulmcgrath just an FYI

**Comment by heypaulmcgrath** [comment]
Sounds good to me

**Comment by giddyelysium** [comment]
Looks good @dennec1 - appreciate it, reads better too.

**Pull request merged**
