### PR TITLE
Update repositorystatus - alphabetize 

### PR DESCRIPTION
**Pull request by fogarl1**
- [ ] I have read the [CONTRIBUTION GUIDE][contributing]
- [ ] This is a bug
- [ ] This is a feature request
- [ ] This is a syntax/style fix
- [ ] This is an improvement to code quality

---
**Please describe your changes below:** 

(Note: A clear description of changes is required to approve any pull requests)
 
_"Changed the implementation for verification because..."_

[contributing]: http://dellemc-symphony.readthedocs.io/en/latest/contributingtosymphony.html

### CODE REVIEW

**Comment by giddyelysium** [comment]
@dennec1 happy to merge?

**Comment by dennec1** [comment]
No - what's the plan with the readme and changelog?

**Comment by giddyelysium** [comment]
Brand new repository, all repositories are Open Source #day 1 :)

**Comment by dennec1** [comment]
No, it doesn't conform with our standards and guidelines, so until we at least get a description for readme, I'd prefer not to push it.  Including @dalys3 to look at this.

**Comment by giddyelysium** [comment]
@dennec1 - Permission to merge now? :)

**Comment by dalys3** [comment]
@giddyelysium - yep, go ahead and merge :)

**Pull request merged**
